[package]
name = "divvy-tracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divvy-core = { version = "0.1.0", path = "../divvy-core" }
tracing = "0.1.37"
