[package]
name = "divvy"
version = "0.1.0"
edition = "2021"

[dependencies]
divvy-core = { version = "0.1.0", path = "divvy-core" }

[features]
default = ["std"]
alloc = ["divvy-core/alloc"]
std = ["alloc", "divvy-core/std"]

[workspace]
members = ["divvy-core"]
